server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/matcher}
    username: ${SPRING_DATASOURCE_USERNAME:matcher}
    password: ${SPRING_DATASOURCE_PASSWORD:matcher}
